apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  namespace: veeresh
  labels:
    type: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: deploy
  template:
    metadata:
      labels:
        type: deploy
    spec:
      containers:
      - name: client
        image: veeresh133/newrepodocker:client
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: veeresh
spec:
  type: NodePort
  selector:
    type: deploy
  ports:
  - port: 5000 
    targetPort: 2000

