apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  namespace: veeresh
  labels:
    type: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: deploy
  template:
    metadata:
      labels:
        type: deploy
    spec:
      containers:
      - name: webapp
        image: kodekloud/webapp-color
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hr-web-app-service
  namespace: veeresh
spec:
  type: NodePort
  selector:
    type: deploy
  ports:
  - port: 8080
    targetPort: 8080
   


