apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: veeresh-autoscale
  namespace: veeresh
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veeryasih-deployment 
  targetCPUUtilizationPercentage: 30
