apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
  namespace: veeresh
spec:
  containers:
  - name: non-root
    image: redis:alpine
  securityContext:
    runAsUser: 1000
    fsGroup: 2000  


































