apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: msg
  name: messaging
  namespace: veeresh
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: veeresh
spec:
  type: ClusterIP
  selector:
    tier: msg
  ports:
  - port: 6379
    targetPort: 6379


























