apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  namespace: veeresh
  labels:
    app: MyApp
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  namespace: veeresh
spec:
  type: ClusterIP
  selector:
    app: MyApp
  ports:
  - port: 80
    targetPort: 80






















