apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  - name: first
    image: nginx
    ports:
    - containerPort: 80
  - name: second
    image: nginx
    ports:
    - containerPort: 80

