apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: veeresh
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: veeresh
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083  
